// Generated by CoffeeScript 1.3.3
var url, _ua;

_ua = (function() {
  var Chrome, IE, IE10, IE6, IE7, IE8, IE9, Safari, Webkit, ltIE6, ltIE7, ltIE8, ltIE9;
  IE = document.uniqueID;
  ltIE6 = typeof window.addEventListener === void 0 && typeof document.documentElement.style.maxHeight === void 0;
  ltIE7 = typeof window.addEventListener === void 0 && typeof document.querySelectorAll === void 0;
  ltIE8 = typeof window.addEventListener === void 0 && typeof document.getElementsByClassName === void 0;
  ltIE9 = IE && typeof window.Worker === void 0;
  IE6 = IE && ltIE6;
  IE7 = IE && ltIE7 && !ltIE6;
  IE8 = IE && ltIE8 && !ltIE7 && !ltIE6;
  IE9 = IE && ltIE9 && !ltIE8 && !ltIE7 && !ltIE6;
  IE10 = IE && !ltIE9 && !ltIE8 && !ltIE7 && !ltIE6;
  Webkit = !document.uniqueID && !window.opera && !window.sidebar && !window.orientation && window.localStorage;
  Safari = Webkit && navigator.vendor.search(/apple/i) !== -1;
  Chrome = Webkit && navigator.vendor.search(/google/i) !== -1;
  return {
    IE: IE,
    ltIE6: ltIE6,
    ltIE7: ltIE7,
    ltIE8: ltIE8,
    ltIE9: ltIE9,
    IE6: IE6,
    IE7: IE7,
    IE8: IE8,
    IE9: IE9,
    IE10: IE10,
    Firefox: window.sidebar,
    Opera: window.opera,
    Webkit: Webkit,
    Safari: Safari,
    Chrome: Chrome,
    Mobile: window.orientation
  };
})();

url = (function() {
  var href, i, j, length, localRegex, path, val, workRegex, _i, _j, _len, _ref;
  href = location.href.split('/');
  localRegex = /^\d+\.\d+\.\d+\.\d+/;
  workRegex = /^.*\/pc\/[^\/]+\/.*$/;
  for (i = _i = 0, _len = href.length; _i < _len; i = ++_i) {
    val = href[i];
    if (val === '' || i === href.length - 1 && val.indexOf('.')) {
      href.splice(i, 1);
    }
  }
  if (localRegex.test(location.hostname) === true || location.hostname.indexOf('localhost') !== -1) {
    length = 2;
  } else if (workRegex.test(location.href) === true) {
    length = 3;
  } else {
    length = 1;
  }
  path = '';
  for (j = _j = 0, _ref = length; 0 <= _ref ? _j <= _ref : _j >= _ref; j = 0 <= _ref ? ++_j : --_j) {
    path += href[j];
    if (j === 0) {
      path += '//';
    } else {
      path += '/';
    }
  }
  return path;
})();

jQuery.extend(jQuery.easing, {
  easeInOutCirc: function(x, t, b, c, d) {
    if ((t /= d / 2) < 1) {
      return -c / 2 * (Math.sqrt(1 - t * t) - 1) + b;
    }
    return c / 2 * (Math.sqrt(1 - (t -= 2) * t) + 1) + b;
  }
});

$(function() {
  var $class, $id, footerHeight;
  $id = $('body').attr('id');
  $class = $('body').attr('class');
  footerHeight = function() {
    var add, height;
    add = 0;
    height = $('#footer').outerHeight();
    $('#content').css('padding-bottom', height + add);
    $('#footer').css('height', height);
  };
  $(window).load(function() {
    setInterval(function() {
      footerHeight();
    }, 100);
  });
  return $('a[href^=#]').click(function(e) {
    $(navigator.userAgent.indexOf('Opera') !== -1 ? (document.compatMode === 'BackCompat' ? 'body' : 'html') : 'html,body').animate({
      scrollTop: $($(this).attr('href')).offset().top - 20
    }, {
      easing: 'easeInOutCirc',
      duration: 1000
    });
    e.preventDefault();
  });
});
